### ISSUE TITLE
FuncTransformer() cannot map pd.series

### ISSUE THREAD

**Issue by stephanobryan** [andersbogsnes/ml_tooling#144]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

def map_series(series, mapping_dict):
    return series.map(mapping_dict)

enh_kode_categorical = ['enh_anvend_kode']
    enh_anvend_kode_dict = {'110': 'Hus', '120': 'Hus', '130': 'Rækkehus',
                            '140': 'Etagebolig', '150': 'Kollegium',
                            '190': 'AndenHeleårsbolig', 9999: 'ukendt'}
enh_kode_categorical_feature_transformer = Pipeline([
        ('select', Select(enh_kode_categorical)),
        ('fill_na', FillNA(value=9999)),
        ('impute', FuncTransformer(map_series, mapping_dict=enh_anvend_kode_dict)),
        ('fill_na_2', FillNA(value='AndreBoligtyper')),
        ('encoder', ToCategorical())
    ])

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

Checklist
---------
- [ X] I have updated ml-tooling to the newest version `pip install ml-tooling --upgrade`
- [X ] I have checked that this issue does not already exist

**Comment by andersbogsnes** [comment]
Hi O'Bryan,

Can you make the code example copy-pastable? e.g define some dummy data and isolate the failing code - otherwise it's hard for us to reproduce.

Pasting the traceback you are getting would be very helpful too!
