### ISSUE TITLE
ENH: Plot confidence intervals of coefs

### ISSUE THREAD

**Issue by andersbogsnes** [andersbogsnes/ml_tooling#190]
We can use the cross-validated scores to bootstrap the confidence interval for each coefficients produced.
If we have the cross-validated coefs - we can do something like:
```python
from sklearn.utils import resample
bootstrapped_coefs = np.mean([resample(cross_val_coefs) for sample in range(n_bootstraps)], axis=0)
percentiles = np.percentiles(bootstrapped_coefs, (2.5, 97.5), axis=0)
```

# API
```python
result = model.score_model()
result.plot.feature_importance()
```

**Comment by thomasfrederikhoeck** [comment]
I don't think this will yield the correct result. The corss_val_coefs are not independent. This will lead to the bootstrapping giving a biased result. Issue #158 is some what related.

**Comment by andersbogsnes** [comment]
closing
