### ISSUE TITLE
Test if plot can use a given .axes

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [andersbogsnes/ml_tooling#204]
#### Problem description

Currently there is no test for supplying .axes to plotting functions.

One test could be to simply test if the plotting is done on the supplied object.

Checklist
---------
- [ ] I have updated ml-tooling to the newest version `pip install ml-tooling --upgrade`
- [ ] I have checked that this issue does not already exist

**Comment by thomasfrederikhoeck** [comment]
See precision-recall curve test for an example. 

```python
    def test_pr_curve_can_use_ax(self, classifier):
        ax = plt.subplot()
        x, y = classifier.result.plot._data.test_x, classifier.result.plot._data.test_y
        y_proba = classifier.model.predict_proba(x)[:, 1]

        assert ax is plot_pr_curve(y, y_proba, ax=ax)

```

**Comment by andersbogsnes** [comment]
Has been generally implemented - closing!
