### ISSUE TITLE
ENH: load_estimator for instance should update instance

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [andersbogsnes/ml_tooling#212]
#### Code Sample, a copy-pastable example if possible

When calling load_estimator on an instance it only returns an object with the estimator. It doesn't update the instance.  This is a bit confussing.

Checklist
---------
- [ ] I have updated ml-tooling to the newest version `pip install ml-tooling --upgrade`
- [ ] I have checked that this issue does not already exist

**Comment by andersbogsnes** [comment]
What would be the expected behavior?
