### ISSUE TITLE
API: What to return when no matching data is found when predicting

### ISSUE THREAD

**Issue by andersbogsnes** [andersbogsnes/ml_tooling#235]
We should make it clear what return value is expected when .make_prediction fails due to invalid data - either because the key doesn't exist or key is malformed.

Should we raise an MLToolingError? A subclassed InvalidInput or something similar?
We could also return 0 or None, but that feels like failing silently...

**Comment by stephanobryan** [comment]
InvalidInput, data doesn't exist or something as informative as possible would be good ;-).
