### ISSUE TITLE
BUG: test estimators default metric error

### ISSUE THREAD

**Issue by Valleo4** [andersbogsnes/ml_tooling#318]
estimators = [create_pipeline(est)
              for est
              in [LinearRegression(),
                  RidgeCV(cv=100),
                  ElasticNetCV(cv=100)]
             ]
best_model, results = Model.test_estimators(data, estimators)

line in boston model notebook yields error:

ValueError: 'default' is not a valid scoring value. Use sorted(sklearn.metrics.SCORERS.keys()) to get valid options.

**Comment by andersbogsnes** [comment]
closed by #340
