### ISSUE TITLE
ENH: confusion matrix with custom probability threshold

### ISSUE THREAD

**Issue by Valleo4** [andersbogsnes/ml_tooling#463]
the `ml_tooling.plot.confusion_matrix` could maybe take a param for a custom probability threshold.

**Comment by andersbogsnes** [comment]
I imagine the API would be something similar to `Result.plot.confusion_matrix(threshold=0.5)`

**Comment by andersbogsnes** [comment]
Maybe the implementation should be in make_prediction? So `model.make_prediction(threshold=0.5)` would trigger a `pred_proba` call and binarize the result using the threshold?

**Comment by Valleo4** [comment]
Yeah, we could do this but we would need to store the predicted classes, this could save a call to predict, as plot.confusion_matrix makes its own predict_proba call.
We would need to do a check that its a classifier, and its a little tricky that we have to select the highest probable class when multiple classes are above the threshold, so its not gonna be pretty.
What do you think?

**Comment by andersbogsnes** [comment]
The multiclass logic would be something along the lines of 
`results[:, np.argmax(results, axis=1)] > threshold`.

It could be factored out into a function that is called both places - but I would stick to just doing the confusion matrix - we can factor it out later

**Comment by stephanobryan** [comment]
I vote for "Result.plot.confusion_matrix(threshold=0.5)", rather than "model.make_prediction(threshold=0.5)".

**Comment by Valleo4** [comment]
@stephanobryan yes thats what were going for, maybe we will implement both, also have #362 

@andersbogsnes yes, except we need the class number and not whether the best class exceeds the threshold (boolean)
