### ISSUE TITLE
ENH: Rare Feature Encoder

### ISSUE THREAD

**Issue by andersbogsnes** [andersbogsnes/ml_tooling#498]
**Is your feature request related to a problem? Please describe.**
When working with categorical data, it is useful to be able to eliminate a number of rarely-occuring categories in order to reduce cardinality

**Describe the solution you'd like**
A Transformer that replaces rare categories with a string such as "Rare"

**Additional context**
Need some kind of threshold for rarity

**Comment by ibenfjord** [comment]
The Transformer is able to replaces categories with a chosen value, if they occur less than a chosen threshold. 

- Nan values are not included, they should be transformed before.
- The threshold can be an int or percentage.  
- Can be used in cross validation and gridsearch.
- Can handle columns which are either not in Train or Test.
