### ISSUE TITLE
BUG: TestMissingDataViz.test_xticklabels_are_correct

### ISSUE THREAD

**Issue by ibenfjord** [andersbogsnes/ml_tooling#533]
**Describe the bug**
Anders guess is that the model does not load

**To Reproduce**
Run tox on Ibens Macbook 

**Additional context**
__________________________________________________________________ TestMissingDataViz.test_xticklabels_are_correct __________________________________________________________________

self = <test_visualize.TestMissingDataViz object at 0x11fad96d0>, ax = <matplotlib.axes._subplots.AxesSubplot object at 0x11fc881f0>

    def test_xticklabels_are_correct(self, ax):
        # Must trigger rendering before labels are accessible
        ax.figure.canvas.draw()
>       assert [text.get_text() for text in ax.get_xticklabels()] == [
            "0.00%",
            "0.50%",
            "1.00%",
            "1.50%",
            "2.00%",
            "2.50%",
        ]
E       AssertionError: assert ['', '', '', '', '', ''] == ['0.00%', '0....00%', '2.50%']
E         At index 0 diff: '' != '0.00%'
E         Use -v to get the full diff

tests/test_visualize.py:635: AssertionError

- [x] I have updated ML Tooling to the latest version
- [x] I have checked if this issue has been reported previously

**Comment by andersbogsnes** [comment]
@ibenfjord is this still an issue?

**Comment by ibenfjord** [comment]
The bug was fixed in pull request "Fix deprecation warnings" #620
