### ISSUE TITLE
Add Binarize Transformer

### ISSUE THREAD

**Issue by andersbogsnes** [andersbogsnes/ml_tooling#76]
Often have instances where I need to replace all instances of a token with 1 and the rest with 0. E.g find all 'J' and replace with 1 and the rest with 0

Simple wrapper around `np.where`:
```python
def transform(self, X):
    return np.where(X == self.value, 1, 0)
```

**Comment by thomasfrederikhoeck** [comment]
Solved in #122 . Should be closed.
