### ISSUE TITLE
Imputing result of Binner

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [andersbogsnes/ml_tooling#92]
Since result of is categorical it is not possible to impute as the following code fails:
```python
import pandas as pd
import numpy as np
import ml_tooling

df = pd.DataFrame({'a':[1,np.nan],'b':[2,3]})

binner = Binner(bins=list(range(0, 3, 1)) )
binner.fit(df)
df_transformed = binner.transform(df)
impute = FillNA(value='Unknown')
impute.fit_transform(df_transformed)

```
with error:
`
raise ValueError("fill value must be in categories")
`

An easy fix could be to add following transformer to the Pipeline:

```python
class AddCategory(BaseEstimator, TransformerMixin):


    def __init__(self, value=None):
        self.value = value

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        for col in X.columns:
            X[col] = X[col].cat.add_categories(self.value)
        return X


```

**Comment by andersbogsnes** [comment]
The question is if we should just write in the docs that to_categorical to be the last step - If you FillNa before ToCategorical, then there is no problem

**Comment by thomasfrederikhoeck** [comment]
ToCategorical hasn't been used here. The problem is that the result of Binner is using the pandas naitve type categorial where you can't add values that doens't exist in the map.

**Comment by andersbogsnes** [comment]
Yup, was in the wrong headspace! 

I'm not a huge fan of adding "tiny" transformers if we can avoid it. 

I see two solutions:
    - Binner adds its own NaN logic, setting NaNs to some value
    - FillNA learns how to handle categoricals, by testing for categorical and inserting the category before 
       replacing

Right off the bat, I'm liking option 2 better - I'm sure this will come up in another context as well!

**Comment by thomasfrederikhoeck** [comment]
I get that. Also there would be very little use for it elsewhere.

I will pursue the second option.

**Comment by thomasfrederikhoeck** [comment]
#94
